name: minerva_analysis
channels:
  - conda-forge
dependencies:
  - Flask=1.1.2
  - flask-sqlalchemy
  - nomkl
  - numpy
  - orjson
  - palettable
  - pandas
  - pillow=8.1.1
  - python=3.8
  - requests
  - scikit-learn
  - scikit-image
  - scipy
  - tifffile=2021.4.8
  - waitress
  - zarr
  - pyinstaller
  - pip
  - pip:
      - ome-types==0.2.0
      - opencv-python



