channels:
  - conda-forge
dependencies:
  - Flask=1.1.2
  - numpy
  - pandas
  - pillow=7.0.0
  - requests
  - scikit-learn
  - scikit-image=0.14.2
  - scipy
  - tifffile
  - pip
  - pip:
      - pyvips
      - opencv-python==4.4.0.*
      - orjson==3.3.0
      - scimap==0.1.11
