name: Install Mac
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          environment-file: requirements.yml
          activate-environment: viewer
      - name: Package Mac
        shell: bash -l {0}
        run: |
           package_mac.sh