name: Package and Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node and Webpack
        run: |
          cd cycif_viewer
          cd client
          npm install
          npm run start
          cd ..
          cd ..
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          environment-file: requirements.yml
          activate-environment: minerva_analysis
      - name: Package Windows
        if: startsWith(matrix.os,'windows')
        shell: cmd /C CALL {0}
        run: |
          package_win.bat
      - name: Package Mac
        if: startsWith(matrix.os,'mac')
        shell: bash -l {0}
        run: |
          ./package_mac.sh
          zip cycif_viewer_mac.zip dist/cycif_viewer_mac
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/cycif_viewer_windows.exe
            cycif_viewer_mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
